export const ROLES = Object.freeze({
  ADMIN: 'ADMIN',
  SUPERVISOR: 'SUPERVISOR',
  CREW: 'CREW',
  CITIZEN: 'CITIZEN'
})

export const CASE_TYPES = Object.freeze({
  LITTER: 'LITTER',
  BULKY: 'BULKY',
  BIN_SERVICE: 'BIN_SERVICE',
  FOLLOW_UP: 'FOLLOW_UP',
  ROUTINE_PICKUP: 'ROUTINE_PICKUP',
  RECYCLABLE: 'RECYCLABLE'
})

export const CASE_STATUSES = Object.freeze({
  PENDING_VALIDATION: 'PENDING_VALIDATION',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  SCHEDULED: 'SCHEDULED',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED',
  CANCELLED: 'CANCELLED'
})

export const TASK_STATUSES = Object.freeze({
  CREATED: 'CREATED',
  ASSIGNED: 'ASSIGNED',
  ARRIVED: 'ARRIVED',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED',
  CANCELLED: 'CANCELLED'
})

export const VEHICLE_TYPES = Object.freeze({
  TRUCK: 'TRUCK',
  SCOOTER: 'SCOOTER'
})

export const REQUIRED_VEHICLE = Object.freeze({
  TRUCK: 'TRUCK',
  SCOOTER: 'SCOOTER',
  CREW_ONLY: 'CREW_ONLY'
})

export const WEEKDAYS = ['MON', 'TUE', 'WED', 'THU', 'FRI', 'SAT', 'SUN']
